truncate table lookups.l_country_code;
insert into lookups.l_country_code values('Andorra','AD');
insert into lookups.l_country_code values('United Arab Emirates','AE');
insert into lookups.l_country_code values('Afghanistan','AF');
insert into lookups.l_country_code values('Antigua and Barbuda','AG');
insert into lookups.l_country_code values('Anguilla','AI');
insert into lookups.l_country_code values('Albania','AL');
insert into lookups.l_country_code values('Armenia','AM');
insert into lookups.l_country_code values('Netherlands Antilles','AN');
insert into lookups.l_country_code values('Angola','AO');
insert into lookups.l_country_code values('ARIPO','AP');
insert into lookups.l_country_code values('Argentina','AR');
insert into lookups.l_country_code values('Austria','AT');
insert into lookups.l_country_code values('Australia','AU');
insert into lookups.l_country_code values('Aruba','AW');
insert into lookups.l_country_code values('Azerbaijan','AZ');
insert into lookups.l_country_code values('Bosnia and Herzegovina','BA');
insert into lookups.l_country_code values('Barbados','BB');
insert into lookups.l_country_code values('Bangladesh','BD');
insert into lookups.l_country_code values('Belgium','BE');
insert into lookups.l_country_code values('Burkina Faso','BF');
insert into lookups.l_country_code values('Bulgaria','BG');
insert into lookups.l_country_code values('Bahrain','BH');
insert into lookups.l_country_code values('Burundi','BI');
insert into lookups.l_country_code values('Benin','BJ');
insert into lookups.l_country_code values('Bermuda','BM');
insert into lookups.l_country_code values('Brunei Darussalam','BN');
insert into lookups.l_country_code values('Bolivia','BO');
insert into lookups.l_country_code values('Brazil','BR');
insert into lookups.l_country_code values('Bahamas','BS');
insert into lookups.l_country_code values('Bhutan','BT');
insert into lookups.l_country_code values('Burma','BU');
insert into lookups.l_country_code values('Bouvet Island','BV');
insert into lookups.l_country_code values('Botswana','BW');
insert into lookups.l_country_code values('BBM and BBDM','BX');
insert into lookups.l_country_code values('Belarus','BY');
insert into lookups.l_country_code values('Belize','BZ');
insert into lookups.l_country_code values('Canada','CA');
insert into lookups.l_country_code values('Central African Republic','CF');
insert into lookups.l_country_code values('Congo','CG');
insert into lookups.l_country_code values('Switzerland','CH');
insert into lookups.l_country_code values('Cote d\'Ivoire','CI');
insert into lookups.l_country_code values('Cook Islands','CK');
insert into lookups.l_country_code values('Chile','CL');
insert into lookups.l_country_code values('Cameroon','CM');
insert into lookups.l_country_code values('China','CN');
insert into lookups.l_country_code values('Colombia','CO');
insert into lookups.l_country_code values('Costa Rica','CR');
insert into lookups.l_country_code values('Czechoslovakia','CS');
insert into lookups.l_country_code values('Cuba','CU');
insert into lookups.l_country_code values('Cape Verde','CV');
insert into lookups.l_country_code values('Cyprus','CY');
insert into lookups.l_country_code values('Czech Republic','CZ');
insert into lookups.l_country_code values('East Germany','DD');
insert into lookups.l_country_code values('Germany','DE');
insert into lookups.l_country_code values('Djibouti','DJ');
insert into lookups.l_country_code values('Denmark','DK');
insert into lookups.l_country_code values('Dominica','DM');
insert into lookups.l_country_code values('Dominican Republic','DO');
insert into lookups.l_country_code values('Algeria','DZ');
insert into lookups.l_country_code values('EAPO','EA');
insert into lookups.l_country_code values('Ecuador','EC');
insert into lookups.l_country_code values('Estonia','EE');
insert into lookups.l_country_code values('Egypt','EG');
insert into lookups.l_country_code values('Western Sahara','EH');
insert into lookups.l_country_code values('OHIM','EM');
insert into lookups.l_country_code values('EPO','EP');
insert into lookups.l_country_code values('Spain','ES');
insert into lookups.l_country_code values('Ethiopia','ET');
insert into lookups.l_country_code values('Finland','FI');
insert into lookups.l_country_code values('Fiji','FJ');
insert into lookups.l_country_code values('Falkland Island','FK');
insert into lookups.l_country_code values('Micronesia','FM');
insert into lookups.l_country_code values('Faroe Islands','FO');
insert into lookups.l_country_code values('France','FR');
insert into lookups.l_country_code values('Gabon','GA');
insert into lookups.l_country_code values('United Kingdom','GB');
insert into lookups.l_country_code values('Grenada','GD');
insert into lookups.l_country_code values('Georgia','GE');
insert into lookups.l_country_code values('Ghana','GH');
insert into lookups.l_country_code values('Gibraltar','GI');
insert into lookups.l_country_code values('Greenland','GL');
insert into lookups.l_country_code values('Gambia','GM');
insert into lookups.l_country_code values('Guinea','GN');
insert into lookups.l_country_code values('Equatorial Guinea','GQ');
insert into lookups.l_country_code values('Greece','GR');
insert into lookups.l_country_code values('South Georgia and The South Sandwich Islands','GS');
insert into lookups.l_country_code values('Guatemala','GT');
insert into lookups.l_country_code values('Guinea-Bissau','GW');
insert into lookups.l_country_code values('Guyana','GY');
insert into lookups.l_country_code values('Hong Kong','HK');
insert into lookups.l_country_code values('Honduras','HN');
insert into lookups.l_country_code values('Croatia','HR');
insert into lookups.l_country_code values('Haiti','HT');
insert into lookups.l_country_code values('Hungary','HU');
insert into lookups.l_country_code values('Volta','HV');
insert into lookups.l_country_code values('IIB','IB');
insert into lookups.l_country_code values('Indonesia','ID');
insert into lookups.l_country_code values('Ireland','IE');
insert into lookups.l_country_code values('Israel','IL');
insert into lookups.l_country_code values('India','IN');
insert into lookups.l_country_code values('Iraq','IQ');
insert into lookups.l_country_code values('Iran','IR');
insert into lookups.l_country_code values('Iceland','IS');
insert into lookups.l_country_code values('Italy','IT');
insert into lookups.l_country_code values('Jamaica','JM');
insert into lookups.l_country_code values('Jordan','JO');
insert into lookups.l_country_code values('Japan','JP');
insert into lookups.l_country_code values('Kenya','KE');
insert into lookups.l_country_code values('Kyrgyzstan','KG');
insert into lookups.l_country_code values('Kampuchea','KH');
insert into lookups.l_country_code values('Kiribati','KI');
insert into lookups.l_country_code values('Comoros','KM');
insert into lookups.l_country_code values('Saint Kitts and Nevis','KN');
insert into lookups.l_country_code values('North Korea','KP');
insert into lookups.l_country_code values('South Korea','KR');
insert into lookups.l_country_code values('Kuwait','KW');
insert into lookups.l_country_code values('Cayman Islands','KY');
insert into lookups.l_country_code values('Kazakhstan','KZ');
insert into lookups.l_country_code values('Laos','LA');
insert into lookups.l_country_code values('Lebanon','LB');
insert into lookups.l_country_code values('Saint Lucia','LC');
insert into lookups.l_country_code values('Liechtenstein','LI');
insert into lookups.l_country_code values('Sri Lanka','LK');
insert into lookups.l_country_code values('Liberia','LR');
insert into lookups.l_country_code values('Lesotho','LS');
insert into lookups.l_country_code values('Lithuania','LT');
insert into lookups.l_country_code values('Luxembourg','LU');
insert into lookups.l_country_code values('Libya','LY');
insert into lookups.l_country_code values('Morocco','MA');
insert into lookups.l_country_code values('Monaco','MC');
insert into lookups.l_country_code values('Moldova','MD');
insert into lookups.l_country_code values('Madagascar','MG');
insert into lookups.l_country_code values('Marshall Islands','MH');
insert into lookups.l_country_code values('Macedonia','MK');
insert into lookups.l_country_code values('Mali','ML');
insert into lookups.l_country_code values('Myanmar','MM');
insert into lookups.l_country_code values('Mongolia','MN');
insert into lookups.l_country_code values('Macao','MO');
insert into lookups.l_country_code values('Northern Mariana Islands','MP');
insert into lookups.l_country_code values('Mauritania','MR');
insert into lookups.l_country_code values('Montserrat','MS');
insert into lookups.l_country_code values('Malta','MT');
insert into lookups.l_country_code values('Mauritius','MU');
insert into lookups.l_country_code values('Maldives','MV');
insert into lookups.l_country_code values('Malawi','MW');
insert into lookups.l_country_code values('Mexico','MX');
insert into lookups.l_country_code values('Malaysia','MY');
insert into lookups.l_country_code values('Mozambique','MZ');
insert into lookups.l_country_code values('Namibia','NA');
insert into lookups.l_country_code values('Niger','NE');
insert into lookups.l_country_code values('Nigeria','NG');
insert into lookups.l_country_code values('Nicaragua','NI');
insert into lookups.l_country_code values('Netherlands(Holland)','NL');
insert into lookups.l_country_code values('Norway','NO');
insert into lookups.l_country_code values('Nepal','NP');
insert into lookups.l_country_code values('Nauru','NR');
insert into lookups.l_country_code values('New Zealand','NZ');
insert into lookups.l_country_code values('OAPI','OA');
insert into lookups.l_country_code values('Oman','OM');
insert into lookups.l_country_code values('Panama','PA');
insert into lookups.l_country_code values('Peru','PE');
insert into lookups.l_country_code values('Papua New Guinea','PG');
insert into lookups.l_country_code values('Philippines','PH');
insert into lookups.l_country_code values('Pakistan','PK');
insert into lookups.l_country_code values('Poland','PL');
insert into lookups.l_country_code values('Portugal','PT');
insert into lookups.l_country_code values('Paraguay','PY');
insert into lookups.l_country_code values('Qatar','QA');
insert into lookups.l_country_code values('Rhodesia','RH');
insert into lookups.l_country_code values('Romania','RO');
insert into lookups.l_country_code values('Russian Federation','RU');
insert into lookups.l_country_code values('Rwanda','RW');
insert into lookups.l_country_code values('Saudi Arabia','SA');
insert into lookups.l_country_code values('Solomon Islands','SB');
insert into lookups.l_country_code values('Seychelles','SC');
insert into lookups.l_country_code values('Sudan','SD');
insert into lookups.l_country_code values('Sweden','SE');
insert into lookups.l_country_code values('Singapore','SG');
insert into lookups.l_country_code values('Saint Helena','SH');
insert into lookups.l_country_code values('Slovenia','SI');
insert into lookups.l_country_code values('Slovakia','SK');
insert into lookups.l_country_code values('Sierra Leone','SL');
insert into lookups.l_country_code values('San Marino','SM');
insert into lookups.l_country_code values('Senegal','SN');
insert into lookups.l_country_code values('Somalia','SO');
insert into lookups.l_country_code values('Suriname','SR');
insert into lookups.l_country_code values('Sao Tome and Principe','ST');
insert into lookups.l_country_code values('Soviet Union','SU');
insert into lookups.l_country_code values('El Salvador','SV');
insert into lookups.l_country_code values('Syria','SY');
insert into lookups.l_country_code values('Swaziland','SZ');
insert into lookups.l_country_code values('Turks and Caicos Islands','TC');
insert into lookups.l_country_code values('Chad','TD');
insert into lookups.l_country_code values('Togo','TG');
insert into lookups.l_country_code values('Thailand','TH');
insert into lookups.l_country_code values('Tajikistan','TJ');
insert into lookups.l_country_code values('Turkmenistan','TM');
insert into lookups.l_country_code values('Tunisia','TN');
insert into lookups.l_country_code values('Tonga','TO');
insert into lookups.l_country_code values('East Timor','TP');
insert into lookups.l_country_code values('Turkey','TR');
insert into lookups.l_country_code values('Trinidad and Tobago','TT');
insert into lookups.l_country_code values('Tuvalu','TV');
insert into lookups.l_country_code values('Taiwan','TW');
insert into lookups.l_country_code values('Tanzania','TZ');
insert into lookups.l_country_code values('Ukraine','UA');
insert into lookups.l_country_code values('Uganda','UG');
insert into lookups.l_country_code values('United States','US');
insert into lookups.l_country_code values('Uruguay','UY');
insert into lookups.l_country_code values('Uzbekistan','UZ');
insert into lookups.l_country_code values('Vatican City','VA');
insert into lookups.l_country_code values('Saint Vincent and the Grenadines','VC');
insert into lookups.l_country_code values('Venezuela','VE');
insert into lookups.l_country_code values('British Virgin Islands','VG');
insert into lookups.l_country_code values('Vietnam','VN');
insert into lookups.l_country_code values('Vanuatu','VU');
insert into lookups.l_country_code values('WIPO','WO');
insert into lookups.l_country_code values('Samoa','WS');
insert into lookups.l_country_code values('Republic of Yemen','YD');
insert into lookups.l_country_code values('Yemen','YE');
insert into lookups.l_country_code values('Yugoslavia','YU');
insert into lookups.l_country_code values('South Africa','ZA');
insert into lookups.l_country_code values('Zambia','ZM');
insert into lookups.l_country_code values('Zaire','ZR');
insert into lookups.l_country_code values('Zimbabwe','ZW');
